### ISSUE TITLE
Q: mootools / Windwalker framework / images -> answered

### ISSUE THREAD

**Issue by mc-cm** [asikart/quickicons#24]
Hi asika!
Thanks for your quickicon extension. It seems extraordinary useful to me and I plan to use it for all my sites.
Two questions arised while I was looking at the code:
* The mootools framework seems to be used by quickicons. At least some mootools files get copied to the site. What for? I thought Joomla! is moving away from mootools.
* additional files (windwalker framework, images, etc.). I realized that a *lot* of files get copied to my joomla installation when installing quickicons. What for? I don't want to bloat up my sites with more scripts and files than necessary. For instance I don't need more that the favicon icons, all other images I'd like to remove. (an idea would be to offer those icons as additional packages).
Sorry for such stupid questions, but first, I'm not a technical person, and - second - I just like to know what is going on my installations. So please give me some insight into those two issues.

Thanks a lot
Chris

**Comment by asika32764** [comment]
For mootools, AQI should only use Joomla core mootools and does not copied new mootools files to site. Some code has written before many years ago, so it will still dependency to mootools until we rewrite it, but it will be a big work since we don't have too many people.

For images, AQI will install some default icon images for use, if you don't want them, just delete `images/quickicons` folder.

For Windwalker Framework, it is a component development tools for our extensions, there are already many 3rd frameworks for extensions similar to it, for example： FOF for Akeeba, Kunena framework for Kunena forum, Nonumber framework for Nonumber extensions etc. 

Maybe it will make a install package too large if we includes them into an extension, but we don't have many people to do same thing again and again, so this way seems necessary in current time for our extensions.

**Comment by mc-cm** [comment]
Hello Askia,

Thanks a lot for your answer. The keypoint to me is that I just can delete the images I don't need. Thanks for that valuable information.
Regarding mootools I saw that actually windwalker seems to come with at least some mootools files. See in *libraries/windwalker/assets/js/mootools/*.

Thanks so far. All the best!
Chris
