### ISSUE TITLE
J3.7 beta 2 error

### ISSUE THREAD

**Issue by micker** [asikart/quickicons#45]
hello in j3.7 beta2
new icon and edit icon return : Fatal error: Class 'JFormFieldList' not found in /home/plomberiym/www/libraries/windwalker/src/Form/Fields/itemlist.php on line 28
thanks for your work

**Comment by asika32764** [comment]
It because JformHelper use `JLoader::register()` instead of `include_once`, so all field file named `list.php` will conflict.

I have already fixed it in RAD framework core and will release all component fixed after 3.7RC released.

If you need fixes it now, follows the change to modify component code.
https://github.com/ventoviro/windwalker-joomla-rad/commit/2f86aa648dddcde6874fb597690c5b8a25f200b0#diff-0a0fee8cccabeb65bde9ad0ffc1fcf34R262

**Comment by asika32764** [comment]
Joomla merged my PR, I think this problem will be fixed in next 3.7 release.

**Comment by micker** [comment]
cool thanks
